IFC:
  encoder:
    type: "operator"
    paras:
      latent: 512
  classfiers:
    type: "mlp"
    numbers: 4
    order: "velocity,angle,size,how long ago?"
    classes: 3 # for every classifer, how many classes

  train:
    optimzer: "Adam"
    lr: 0.001
    num_epochs: 500
    e_stops: 10
    batch_size: 24

  Data_In:
    seq_len: 10 # 20*0.05=1s
    spatial_x: 64
    spatial_y: 100
    T_prime_max: 30
    train_path: "/root/autodl-tmp/HSPS/IFC/Dataset/225_cases/Train_augment_3375_cases.npz"
    test_path: "/root/autodl-tmp/HSPS/IFC/Dataset/225_cases/Test_augment_216_cases.npz"
  Save:
    path: "Checkpoints/Operator/Multi-task/IFC_Opertor_N_10_Tprime_30"
