IFC:
  encoder:
    type: "transformer"
    paras:
      nheads: 2
      num_layers: 1
      latent: 512
  classfiers:
    type: "mlp"
    numbers: 4
    order: "velocity,angle,size,how long ago?"

  train:
    optimzer: "Adam"
    lr: 0.001
    num_epochs: 500
    e_stops: 100
    batch_size: 50

  Data_In:
    seq_len: 30
    spatial_x: 64
    spatial_y: 64
    path: "/root/autodl-tmp/HSPS/IFC/Dataset/245_cases/Data.npz"
  Save:
    path: "Checkpoints/IFC_transformer_N_30"
